<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mahasiswa_model extends CI_Model
{

    public $table = 'mahasiswa';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    

    // get all
    function getMahasiswa($table)
    {
        $data = $this->db->get($table);
        return $data->result_array();
    }




}

/* End of file Nani_model.php */
/* Location: ./application/models/Nani_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-04 10:46:01 */
/* http://harviacode.com */